### PR TITLE
First edition of proposal for dns trait

### LINKED ISSUE #8: Support trait for DNS
Would it make sense to add a support trait for DNS lookups?

Somthing along the lines of
```rust
pub trait Dns {
    /// The type returned when we have an error
    type Error: core::fmt::Debug;

    fn resolve(&self, hostname: &str) -> Result<IpAddr, Self::Error>;
}
```

### PR DESCRIPTION
**Pull request by MathiasKoch**
This PR provides a simple DNS trait, similar to that provided by both `lwip` and the `Berkeley sockets API`, consisting of a simple `gethostbyname` function that resolves a hostname to the first ip address given by `A` or `AAAA` DNS record, depending on the requested `addr_type`, and a `gethostbyaddr` to resolve the hostname given an ip address. The later function has the `addr_type` encoded in the given `IpAddr` input.

This is a proposal for a first edition. It will not cover the full DNS, but it is equivalent of both `lwip` and the `Berkeley sockets API`, as well as the functionality given by `std::net::ToSocketAddrs`

Fixes #8

### CODE REVIEW

File: src/dns.rs [hunk 1]
```diff
@@ -0,0 +1,41 @@
+use no_std_net::IpAddr;
+use heapless::{String, consts};
+
+/// This is the host address type to be returned by `gethostbyname`.
+///
+/// An IPv4 address type always looks for `A` records, while IPv6 address type
+/// will look for `AAAA` records
+#[derive(Clone, Debug, PartialEq)]
+pub enum AddrType {
```
Comment (thejpster) [inline src/dns.rs:9]: Is there anything in `no_std_net` we can use here. Feels like we're re-inventing the wheel?

Comment (thejpster) [reply src/dns.rs:9]: Also, should we support an 'Either' option, in case you support both and don't mind either? I think you can ask a DNS sever for both AAAA and A records at the same time, so this would be more efficient than asking for one then the other.

**Review by thejpster — CHANGES_REQUESTED** [review]
Just a comment on the AddrType type.

File: src/dns.rs (hunk 1 above)
Comment (MathiasKoch) [reply src/dns.rs:9]: I had sort of the same feeling, but they don't define anything like this. All they have is the `IpAddr` and `SocketAddr`, and the variants in both hold `Ipv4Addr/Ipv6Addr` and `SocketAddrV4/SocketAddrV6`.

> Also, should we support an 'Either' option, in case you support both and don't mind either? I think you can ask a DNS sever for both AAAA and A records at the same time, so this would be more efficient than asking for one then the other.

I think this makes sense. An alternative could be to change `addr_type` in `gethostbyname` to `Option<AddrType>`? Where `None` actually means either. Not sure which is better?

Comment (MathiasKoch) [reply src/dns.rs:9]: @thejpster Did you have any opinions on adding an `Either` vs changing it to an `Option`? See above comment.

Comment (thejpster) [reply src/dns.rs:9]: Sorry, I'm not on Github much any more. I think I prefer `Either|IPv6|IPv4` over `Some(IPv4|IPv6)|None`, as `None` sounds you like don't want either, as opposed to both.

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
LGTM!
